export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART"
export const DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART"


export const ADD_ITEM_TO_CART_REQUEST = "ADD_ITEM_TO_CART_REQUEST"
export const DELETE_ITEM_FROM_CART_REQUEST = "DELETE_ITEM_FROM_CART_REQUEST"

export const CHANGE_CURRENT_QUANTITY = "CHANGE_CURRENT_QUANTITY"

