export const GET_PRODUCT_BY_CATEGORY_REQUEST = "GET_PRODUCT_BY_CATEGORY_REQUEST"
export const GET_PRODUCT_BY_CATEGORY_SUCCESS = "GET_PRODUCT_BY_CATEGORY_SUCCESS"

// export const SORT_BY_NEW_BOOK_FOR_CATEGORY_REQUEST = "SORT_BY_NEW_BOOK_FOR_CATEGORY_REQUEST"
// export const SORT_BY_NEW_BOOK_FOR_CATEGORY_SUCCESS = "SORT_BY_NEW_BOOK_FOR_CATEGORY_SUCCESS"

export const CHANGED_PAGE_CATRGORY_COUNT = "CHANGED_PAGE_CATRGORY_COUNT"







 