export const API_ERROR = "API_ERROR"
export const SET_PORCCESSING = "SET_PORCCESSING"
export const GET_ALL_PRODUCTS_REQUEST = "GET_ALL_PRODUCTS_REQUEST"
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS"
export const GET_PRODUCT_BY_ID_REQUEST = "GET_PRODUCT_BY_ID_REQUEST"
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS"

export const DISABLED_BUTTON_ADD_TO_CART = "DISABLED_BUTTON_ADD_TO_CART"
export const ENABLED_BUTTON_ADD_TO_CART = "ENEBLED_BUTTON_ADD_TO_CART"


export const CHANGED_CURRENT_SEARCH_VALUE = "CHANGED_CURRENT_SEARCH_VALUE" 

export const CHANGED_PAGE_COUNT = "CHANGED_PAGE_COUNT"

export const SORT_BY_NEW_BOOK_REQUEST = "SORT_BY_NEW_BOOK_REQUEST"
export const SORT_BY_NEW_BOOK_SUCCESS = "SORT_BY_NEW_BOOK_SUCCESS"

export const GO_HOME = "GO_HOME"











 