export const GET_PRODUCT_BY_CATEGORY_REQUEST = "GET_PRODUCT_BY_CATEGORY_REQUEST"
export const GET_PRODUCT_BY_CATEGORY_SUCCESS = "GET_PRODUCT_BY_CATEGORY_SUCCESS"
export const API_ERROR = "API_ERROR"
export const SET_PORCCESSING = "SET_PORCCESSING"
export const GET_ALL_PRODUCTS_REQUEST = "GET_ALL_PRODUCTS_REQUEST"
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS"
export const GET_PRODUCT_BY_ID_REQUEST = "GET_PRODUCT_BY_ID_REQUEST"
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS"

export const FILLTER_PRICE_LOW_TO_HIGHT = "FILLTER_PRICE_LOW_TO_HIGHT"
export const FILLTER_PRICE_HIGHT_TO_LOW = "FILLTER_PRICE_HIGHT_TO_LOW"

export const ITEM_ADDED_TO_CART = "ITEM_ADDED_TO_CART"
export const ITEM_DELETED_FROM_CART = "ITEM_DELETED_FROM_CART"








 